project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: about.qmd
        text: Second Page
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



